// P — Produce: Generate code that satisfies the test matrix
// Copyright 2026 Chad Hendren. All Rights Reserved.

import type { BuildPlan, ProduceResult } from "../types.ts";

/** Generate test file content from a test matrix */
export function generateTestFile(plan: BuildPlan): string {
  const lines: string[] = [
    'import { describe, it, expect } from "vitest";',
    "",
    'describe("Generated Tests", () => {',
  ];

  for (const test of plan.testMatrix) {
    lines.push(`  it("${test.id}: ${test.description}", () => {`);
    lines.push(`    // Priority: ${test.priority}`);
    lines.push(`    // Requirement: ${test.requirementId}`);
    lines.push(`    // Input: ${test.input}`);
    lines.push(`    // Expected: ${test.expectedOutput}`);
    lines.push("    expect(true).toBe(true); // TODO: implement");
    lines.push("  });");
    lines.push("");
  }

  lines.push("});");
  return lines.join("\n");
}

/** Generate implementation scaffold from build plan */
export function generateScaffold(plan: BuildPlan): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = [];

  for (const component of plan.components) {
    const fileName = component.name.replace(/[^a-z0-9-]/g, "-");
    files.push({
      path: `src/${fileName}.ts`,
      content: [
        `// ${component.responsibility}`,
        `// Auto-generated by RALPH Loop — Produce phase`,
        "",
        `export function ${toCamelCase(component.name)}() {`,
        `  // TODO: Implement ${component.responsibility}`,
        `  throw new Error("Not implemented");`,
        "}",
        "",
      ].join("\n"),
    });
  }

  return files;
}

function toCamelCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word, i) => i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

/** Run the Produce phase */
export function produce(plan: BuildPlan): ProduceResult {
  const scaffold = generateScaffold(plan);
  const testContent = generateTestFile(plan);

  return {
    files: scaffold,
    testFiles: [{ path: "tests/generated.test.ts", content: testContent }],
  };
}
